# Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_log_monitor?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.initialization-mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.sqlScriptEncoding=UTF-8
spring.jpa.properties.hibernate.jdbc.time_zone = UTC
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.contexts=dev
# SERVER
#server.servlet.context-path=/nails-api
server.port = 8787
spring.main.allow-bean-definition-overriding=true
#spring.jackson.serialization.INDENT_OUTPUT= true
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#EXCEPTION HANDLER
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false


#LOG
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.level.root=WARN
logging.level.log.monitor.api=DEBUG
logging.level.org.springframework.web=WARN
logging.file.path=logs/
logging.file.name=logs/log.log
logging.file=${catalina.home}/logs/spam.log


#EMAIL
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=duongthitruclinh932@gmail.com
spring.mail.password=taqpzuqxrydaweoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Feign client
feign.client.config.default.connectTimeout=60000
feign.client.config.default.readTimeout=60000

#APP CONFIG
qrauth.auth.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAspaDTSYZvihLpmKp/ZCG\ny0hnzPT5ul9pC/3KHbGBcDZYLaZ4ZNPXoOF/S1zCGuwIH6eShBBx7mhyMyO7a3Fb\n0hD+f5GwonhhpoMuNCm/YR3lN6wXKSW9+GjbOUxbFVWBD1eEfJQIqr0lTMaqRc0N\nGBpvigk3ofNheZUV/eCFoht1+zyOuclJQPZHJbbnp1p+m9C2+P1FqAtDEV4VgSRL\n1JS8OR7YlRT9BbKKFcDVLan8yhMn+J0WOW5od7WCuSoziPoC81kne6TPbju+WKwu\n7/lShFZB7GLqUawmX+qbm2hsqPUu4bCNhFnkoot9i0m39OahaKhffYU3ERcFSOrQ\n9wIDAQAB
jwt.version=1

# Async Config
thread.pool.size=10
thread.pool.queue.size=150

# SSO
sso.internal.base.url=https://sso-api-vbook.itz.io.vn/

sso.basic.username=abc_client
sso.basic.password=abc123
sso.app.secretId=abl8q5kctfhpuza6ouxet4wdkhnmrr03qtijkvu5mfmj7zqgpi4dt3bgcefvko4ezzsufxtbatmatmgazntmu95owrzmwnz7lvxrhvbiit74qsmwvzi4qtyf0fhwsbwk
sso.app.id=9762425236291584

# Media service
media.internal.base.url=https://api-mediabucket.itz.io.vn

# VictoriaLogs error-alert scheduler
victorialogs.api.url=https://victorialogs.moviehub.io.vn

# slack
slack.api.url=https://slack.com/api

# telegram
telegrambots.api.url=https://api.telegram.org
